- glmaster/usr/bin/glmaster/MasterDaemon.py
> fix prev sonos

- www/templates/default/include/conf_device.php
fix save options in conf_device
> fix save options in conf_device

- glmaster/usr/bin/glmaster/MasterDaemon.py
- glslave/usr/lib/domoleaf/DeviceManager.py
- glslave/usr/lib/domoleaf/HttpReq.py
- www/form/form_mc_camera.php
- www/js/touch.js
- www/libs/Api.class.php
- www/libs/User.class.php
- www/templates/default/popup/popup_camera_view.php
> add move camera

- www/libs/Admin.class.php
- www/templates/default/popup/popup_rename_daemon.php
> fix protocol interface

- glmaster/usr/bin/glmaster/MasterDaemon.py
- glslave/usr/bin/glslave/SlaveDaemon.py
- www/form/form_d3_reboot.php
- www/libs/Admin.class.php
- www/libs/Api.class.php
- www/templates/default/include/conf_daemon.php
- www/templates/default/popup/popup_reboot_d3.php
add button reboot D3 on box configuration
> add button reboot D3 on box configuration

- www/libs/Admin.class.php
- www/libs/Api.class.php
- www/libs/User.class.php
- www/templates/default/design.css
- www/templates/default/form/form_custom_delete_device.php
- www/templates/default/form/form_custom_delete_room.php
- www/templates/default/form/form_custom_upload_room.php
- www/templates/default/header/profile_user_installation.php
- www/templates/default/include/conf_user_permission.php
- www/templates/default/include/profile_user_installation.php
- www/templates/default/include/profile_user_scenarios.php
- www/templates/default/popup/popup_custom_device.js
- www/templates/default/popup/popup_custom_device.php
- www/templates/default/scripts.js
Added upload image for Room customisation and little fixes on Uploads.
> Room customisation

- www/form/form_floor_new.php
- www/form/form_room_new.php
- www/libs/Admin.class.php
- www/libs/Api.class.php
- www/templates/default/design.css
- www/templates/default/include/conf_installation.php
- www/templates/default/popup/popup_new_floor.php
- www/templates/default/popup/popup_user_create_scenario.php
- www/templates/default/popup/popup_user_create_schedule.php
- www/templates/default/popup/popup_user_create_smartcmd.php
- www/templates/default/popup/popup_user_create_trigger.php
- www/templates/default/popup/popup_user_update_scenario_name.php
- www/templates/default/popup/popup_user_update_schedule_name.php
- www/templates/default/popup/popup_user_update_smartcmd_name.php
- www/templates/default/popup/popup_user_update_trigger_name.php
Changed popup for adding a new floor
> Creating 1st room when creating a floor

- www/form/form_mc_reset_error.php
- www/libs/Admin.class.php
- www/libs/Api.class.php
- www/libs/User.class.php
- www/templates/default/function/display_widget.php
- www/templates/default/include/home.php
- www/templates/default/popup/popup_info_device.php
- www/templates/default/scripts.js
add posibility for admins to reset an error in popup info-device
> add posibility for admins to reset an error in popup info-device

- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/top_connected.php
> Fixed some translations

- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/form/form_conf_list_db.php
- www/templates/default/form/form_list_devices_of_room.php
- www/templates/default/form/form_list_rooms_of_floor.php
- www/templates/default/function/display_widget.php
- www/templates/default/header/profile_user_graphics.php
- www/templates/default/popup/popup_new_floor.php
- www/templates/default/popup/popup_new_room.php
- www/templates/default/popup/popup_remove_scenario.php
- www/templates/default/popup/popup_remove_schedule.php
- www/templates/default/popup/popup_remove_smartcmd.php
- www/templates/default/popup/popup_remove_smartcmd_elem.php
- www/templates/default/popup/popup_remove_trigger.php
- www/templates/default/popup/popup_remove_trigger_elem.php
- www/templates/default/popup/popup_rename_room.php
- www/templates/default/popup/popup_user_create_scenario.php
- www/templates/default/popup/popup_user_create_schedule.php
- www/templates/default/popup/popup_user_create_smartcmd.php
- www/templates/default/popup/popup_user_create_trigger.php
- www/templates/default/popup/popup_user_update_scenario_name.php
- www/templates/default/popup/popup_user_update_schedule_name.php
- www/templates/default/popup/popup_user_update_smartcmd_name.php
- www/templates/default/popup/popup_user_update_trigger_name.php
Fixed translations and other minor fixes
> Fixed translations and other minor fixes

- www/libs/Admin.class.php
- www/libs/Api.class.php
- www/libs/User.class.php
- www/templates/default/design.css
- www/templates/default/form/form_update_bg_color.php
- www/templates/default/header/conf_user_permission.php
- www/templates/default/header/home.php
- www/templates/default/header/profile_user_installation.php
- www/templates/default/include/conf_device_new.php
- www/templates/default/include/conf_room.php
- www/templates/default/include/conf_user_permission.php
- www/templates/default/include/home.php
- www/templates/default/include/profile_user_installation.php
- www/templates/default/popup/popup_ChromaWheel.php
- www/templates/default/scripts.js
Added color customisation for MasterCommand sidebar & fixed translations
> Added color customisation for MasterCommand sidebar

- www/templates/default/function/display_widget.php
fix :
- Display name of 'Passerelle KNX/IR' with any protocol
- add some widgets missing
> fix in 'display_widget'

- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/design.css
- www/templates/default/form/form_show_scenario_summary.php
- www/templates/default/form/form_user_smartcmd_opt_list.php
- www/templates/default/include/profile_user_smartcmd_edit.php
- www/templates/default/popup/popup_custom_device.php
- www/templates/default/popup/popup_remove_device.php
- www/templates/default/popup/popup_remove_smartcmd_elem.php
- www/templates/default/scripts.js
-Fixed Scenario bug (validation without smartcommand was possible)
-Add popup title and upload condition text in Popup Custom Upload
-Changed Smartcommand Interface 
Options now appears in the left menu, below the device they belong.
(so, removed bottom navbar)
-Added popup loading when displaying smartcommand
> Littles fixes & interface change in Smartcommand

- www/form/form_profile_save.php
- www/form/form_user_new.php
- www/libs/Admin.class.php
- www/libs/Api.class.php
- www/libs/User.class.php
- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/header/conf_profiles.php
- www/templates/default/include/conf_profiles.php
- www/templates/default/include/profile.php
add posibility for admin to change lvl for each (except themselves) user and the input email
> add posibility for admin to change lvl for each user and the input email

- www/functions.php
- www/libs/Admin.class.php
- www/libs/Api.class.php
- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/form/form_conf_room_device_list.php
- www/templates/default/include/conf_device_new.php
- www/templates/default/include/conf_installation.php
- www/templates/default/popup/popup_new_floor.php
add multiple input default and add button edit
> add multiple input default and add button edit

- www/libs/Admin.class.php
- www/libs/User.class.php
- www/templates/default/function/display_widget.php
- www/templates/default/include/conf_device.php
- www/templates/default/popup/popup_info_device.php
> multiple fix

- domomaster/usr/bin/domomaster/KNXManager.py
- domomaster/usr/bin/domomaster/MasterSql.py
Update ip_addr for device dynamicaly (base on mac) ; Fix option fan for 8 bits
> Update ip_addr for device dynamicaly and fix fan

- www/libs/Api.class.php
- www/libs/User.class.php
- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/design.css
- www/templates/default/form/form_create_new_smartcmd.php
- www/templates/default/form/form_list_rooms_of_floor.php
- www/templates/default/header/profile_user_smartcmd.php
- www/templates/default/include/profile_user_graphics.php
- www/templates/default/include/profile_user_scenario_edit.php
- www/templates/default/include/profile_user_smartcmd_edit.php
- www/templates/default/popup/popup_user_create_smartcmd.php
Added edit button in Scenario edition lists
Added choice of Linked Room in the "New Smartcommand" popup
> Fixes & Improves

- dists/debian/domoslave.control
- dists/ubuntu/precise/domoslave.control
- domomaster/usr/bin/domomaster/domomaster_postinst.py
- domoslave/usr/bin/domoslave/SlaveDaemon.py
- domoslave/usr/lib/domoleaf/MysqlHandler.py
- www/templates/default/include/conf_daemon.php
- www/templates/default/popup/popup_wifi.php
Add completely access point for wifi and fix on config wifi and access to DB
> Add completely access point for wifi and fix on config wifi and access to DB 

- www/form/form_device_new.php
- www/libs/Admin.class.php
- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/include/conf_device_new.php
Fix when a bad address is enter for a new device and a merge
> Fix when a bad address is enter for a new device

- domomaster/usr/bin/domomaster/MasterDaemon.py
- domoslave/usr/bin/domoslave/SlaveDaemon.py
- www/form/form_d3_reboot.php
- www/libs/Admin.class.php
- www/libs/Api.class.php
- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/include/conf_daemon.php
- www/templates/default/popup/popup_reboot_d3.php
- www/templates/default/popup/popup_shutdown_d3.php
add client mode for wifi and the functionality to shutdown D3
> add client mode for wifi and the functionality to shutdown D3

- monitor_enocean/Makefile
- monitor_enocean/enocean_init.c
- monitor_enocean/enocean_packet_functions.c
- monitor_knx/Makefile
> fixes EnOcean and KNX

- domomaster/etc/domoleaf/sql/create/dpt_optiondef.sql
> Removed bad dpt

- www/css/flaticon.css
- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/include/conf_db.php
- www/templates/default/top_connected.php
Fixed "USB Backup" button in conf_db
Changed top menu : 
Added :
- Smartcommand and Help
- Master Command icon
- Bigger texts
> Changed top menu & little fix

- www/libs/User.class.php
> Fixed Disconnect

- www/templates/default/include/signin.php
> Add focus on signin

- www/templates/default/popup/popup_conf_db_usb.php
- www/templates/default/popup/popup_list_db_usb.php
> Fixed USB backup popup

- domomaster/etc/nginx/sites-available/domoleaf.conf
- domomaster/usr/bin/domomaster/MasterDaemon.py
- domoslave/usr/lib/domoleaf/CalcLogs.py
- domoslave/usr/lib/domoleaf/Scenario.py
- www/locales/fr_FR/LC_MESSAGES/messages.po
- www/templates/default/form/form_display_trigger.php
- www/templates/default/form/form_trigger_device_option.php
- www/templates/default/form/form_user_trigger_opt_list.php
- www/templates/default/header/profile_user_trigger_events_edit.php
- www/templates/default/include/profile_user_smartcmd_edit.php
- www/templates/default/include/profile_user_trigger_events_edit.php
- www/templates/default/popup/popup_trigger_device_option.php
- www/templates/default/scripts.js
> Fixes & Additions to Triggers

- domomaster/usr/bin/domomaster/MasterDaemon.py
- locales/fr_FR/messages.po
- www/libs/Admin.class.php
- www/libs/Api.class.php
- www/libs/User.class.php
- www/templates/default/form/form_general_date_time.php
- www/templates/default/include/conf_general.php
- www/templates/default/popup/popup_modif_datetime.php
Add new Popup for manual modifications of the date and time
Added French translations
> Add new Popup for manual modifications of the date and time

- domomaster/usr/bin/domomaster/EnOceanManager.py
- domomaster/usr/bin/domomaster/KNXManager.py
- domomaster/usr/bin/domomaster/MasterDaemon.py
- domoslave/usr/bin/domoslave/SlaveDaemon.py
- domoslave/usr/lib/domoleaf/CalcLogs.py
- domoslave/usr/lib/domoleaf/DaemonConfigParser.py
- domoslave/usr/lib/domoleaf/IP_IRManager.py
- domoslave/usr/lib/domoleaf/Scanner.py
- domoslave/usr/lib/domoleaf/Scenario.py
- domoslave/usr/lib/domoleaf/Schedule.py
- domoslave/usr/lib/domoleaf/Smartcommand.py
- domoslave/usr/lib/domoleaf/Trigger.py
> Clean logs
